export const ERROR_CODE_MESSAGES: Record<string, string> = {
    UNKNOWN_ERROR: "An unexpected error occurred.",
    INTERNAL_SERVER_ERROR: "Internal server error. ",
    ARGUMENT_INVALID_ERROR: "One or more provided arguments are invalid.",
    TITLE_BLANK_ERROR: "The movie title cannot be empty.",
    TITLE_MAX_SIZE_ERROR: "The movie title exceeds the maximum allowed character limit.",
    RELEASE_YEAR_NULL_ERROR: "The release year must be specified.",
    RELEASE_YEAR_MIN_ERROR: "The release year cannot be earlier than the dawn of cinema (1888).",
    RELEASE_YEAR_MAX_ERROR: "The release year cannot be set in the distant future.",
    DIRECTORS_EMPTY_ERROR: "You must add at least one director.",
    DIRECTORS_ITEMS_BLANK_ERROR: "Director names cannot be empty or blank spaces.",
    DIRECTORS_MAX_SIZE_ERROR: "You have added too many directors.",
    GENRES_EMPTY_ERROR: "You must select at least one genre.",
    GENRES_ITEMS_BLANK_ERROR: "Genre names cannot be empty or blank spaces.",
    GENRES_ITEMS_INVALID_ERROR: "One or more selected genres are not recognized.",
    PLOT_BLANK_ERROR: "The movie plot description cannot be empty.",
    PLOT_MAX_SIZE_ERROR: "The plot description is too long. Please keep it concise.",
    IDENTIFIER_BLANK_ERROR: "Username or email identifier cannot be empty.",
    IDENTIFIER_MAX_SIZE_ERROR: "The identifier exceeds the maximum allowed length.",
    PASSWORD_BLANK_ERROR: "Password cannot be empty.",
    PASSWORD_MAX_SIZE_ERROR: "Password exceeds the maximum allowed length.",
    REFRESH_TOKEN_BLANK_ERROR: "Authentication refresh token is missing.",
    RATING_NULL_ERROR: "A valid rating must be provided.",
    RATING_MIN_ERROR: "The rating provided is below the minimum allowed value (1).",
    RATING_MAX_ERROR: "The rating provided exceeds the maximum allowed value (10).",
    EXCLUDED_GENRES_ITEMS_BLANK_ERROR: "Excluded genre names cannot be blank.",
    EXCLUDED_GENRES_ITEMS_INVALID_ERROR: "One or more excluded genres are not recognized.",
    MIN_RELEASE_YEAR_MIN_ERROR: "The minimum release year filter is too far in the past.",
    MIN_RELEASE_YEAR_MAX_ERROR: "The minimum release year filter cannot be in the future.",
    USERNAME_BLANK_ERROR: "Username cannot be empty.",
    USERNAME_MIN_SIZE_ERROR: "Username is too short.",
    USERNAME_MAX_SIZE_ERROR: "Username is too long.",
    USERNAME_INVALID_ERROR: "Username contains invalid characters.",
    EMAIL_BLANK_ERROR: "Email address cannot be empty.",
    EMAIL_MIN_SIZE_ERROR: "Email address is too short.",
    EMAIL_MAX_SIZE_ERROR: "Email address is too long.",
    EMAIL_INVALID_ERROR: "Please provide a valid email address format.",
    PASSWORD_MIN_SIZE_ERROR: "Password is too short. Please use a longer password for better security.",
    PASSWORD_PATTERN_1_ERROR: "Password must contain at least one uppercase letter (A-Z).",
    PASSWORD_PATTERN_2_ERROR: "Password must contain at least one lowercase letter (a-z).",
    PASSWORD_PATTERN_3_ERROR: "Password must contain at least one number (0-9).",
    PASSWORD_PATTERN_4_ERROR: "Password must contain at least one special character.",
    PASSWORD_PATTERN_5_ERROR: "Password must not contain blank spaces or invalid symbols.",
    USER_UNAUTHORIZED_ERROR: "You are not authorized to perform this action. Please log in.",
    MOVIE_ID_POSITIVE_ERROR: "The movie ID must be a positive number.",
    MOVIE_CONFLICT_ERROR: "This movie already exists in your watchlist.",
    CREDENTIALS_INVALID_ERROR: "Invalid username or password.",
    MOVIE_NOT_FOUND_ERROR: "The requested movie could not be found in your watchlist.",
    REFRESH_TOKEN_INVALID_ERROR: "Your session has expired.",
    USERNAME_CONFLICT_ERROR: "This username is already taken.",
    EMAIL_CONFLICT_ERROR: "An account with this email address already exists.",
    MOVIE_ID_NULL_ERROR: "The movie ID cannot be null.",
    MOVIE_ID_MIN_ERROR: "The movie ID must be greater than zero."
};

export const mapErrorCode = (code: string): string => {
    return ERROR_CODE_MESSAGES[code] || ERROR_CODE_MESSAGES["UNKNOWN_ERROR"];
};